export interface MinorCategory {
  id: string;
  /** Short uppercase code shown on each card, e.g. "AUTH". */
  code: string;
  label: string;
  projects: string[];
}

export const MINOR_CATEGORIES: MinorCategory[] = [
  {
    id: "auth",
    code: "AUTH",
    label: "Authentication & User Management",
    projects: [
      "Smart Login System",
      "JWT Authentication Portal",
      "Multi-Role Dashboard",
      "User Profile Manager",
      "Password Manager",
      "OTP Verification System",
      "Email Verification Portal",
      "Session Tracker",
      "Account Activity Monitor",
      "Biometric Login Simulator",
    ],
  },
  {
    id: "productivity",
    code: "PROD",
    label: "Productivity",
    projects: [
      "Task Management App",
      "Smart To-Do List",
      "Daily Planner",
      "Habit Tracker",
      "Pomodoro Timer",
      "Goal Tracking System",
      "Notes Management App",
      "Sticky Notes Board",
      "Calendar Scheduler",
      "Meeting Planner",
    ],
  },
  {
    id: "ai",
    code: "AI",
    label: "AI-Based",
    projects: [
      "AI Resume Analyzer",
      "AI Cover Letter Generator",
      "AI Chat Assistant",
      "AI Code Reviewer",
      "AI Email Writer",
      "AI Document Summarizer",
      "AI Interview Assistant",
      "AI Grammar Checker",
      "AI Study Planner",
      "AI Image Caption Generator",
    ],
  },
  {
    id: "education",
    code: "EDU",
    label: "Education",
    projects: [
      "Student Management System",
      "Online Quiz Platform",
      "Attendance Management",
      "Course Recommendation Portal",
      "Assignment Tracker",
      "Digital Library",
      "Online Examination System",
      "Grade Calculator",
      "Teacher Dashboard",
      "Learning Progress Tracker",
    ],
  },
  {
    id: "finance",
    code: "FIN",
    label: "Finance",
    projects: [
      "Expense Tracker",
      "Personal Budget Manager",
      "Bill Reminder System",
      "EMI Calculator",
      "Investment Portfolio Tracker",
      "Expense Analytics Dashboard",
      "Loan Calculator",
      "Subscription Tracker",
      "Income Tax Calculator",
      "Invoice Generator",
    ],
  },
  {
    id: "healthcare",
    code: "MED",
    label: "Healthcare",
    projects: [
      "Appointment Booking System",
      "Medicine Reminder",
      "Hospital Management Mini",
      "BMI Calculator",
      "Health Record Manager",
      "Blood Donation Portal",
      "Fitness Tracker",
      "Calorie Counter",
      "Symptom Checker",
      "Water Intake Tracker",
    ],
  },
  {
    id: "ecommerce",
    code: "COMM",
    label: "E-Commerce",
    projects: [
      "Mini E-Commerce Store",
      "Shopping Cart System",
      "Product Inventory Manager",
      "Order Tracking System",
      "Coupon Management",
      "Wishlist Manager",
      "Product Review Platform",
      "Vendor Dashboard",
      "Digital Marketplace",
      "Grocery Store Portal",
    ],
  },
  {
    id: "social",
    code: "SOC",
    label: "Social & Communication",
    projects: [
      "Real-Time Chat App",
      "Community Forum",
      "Anonymous Confession App",
      "Blogging Platform",
      "Event Discussion Board",
      "Friend Recommendation System",
      "Group Chat Application",
      "Poll & Voting System",
      "Social Feed App",
      "Team Collaboration Tool",
    ],
  },
  {
    id: "business",
    code: "BIZ",
    label: "Business",
    projects: [
      "CRM Dashboard",
      "Employee Management System",
      "Leave Management Portal",
      "Payroll Calculator",
      "Visitor Management System",
      "Asset Tracking System",
      "Office Inventory Manager",
      "HR Recruitment Portal",
      "Project Management Dashboard",
      "Client Management System",
    ],
  },
  {
    id: "realtime",
    code: "LIVE",
    label: "Real-Time",
    projects: [
      "Live Weather Dashboard",
      "Crypto Price Tracker",
      "Stock Market Dashboard",
      "Live Sports Score App",
      "News Aggregator",
      "Traffic Monitoring Dashboard",
      "Currency Converter",
      "Live Flight Tracker",
      "COVID Statistics Dashboard",
      "Earthquake Alert System",
    ],
  },
  {
    id: "utility",
    code: "UTIL",
    label: "Utility",
    projects: [
      "URL Shortener",
      "QR Code Generator",
      "File Sharing App",
      "PDF Merger Tool",
      "Image Compressor",
      "Password Generator",
      "Text Encryption Tool",
      "Markdown Editor",
      "JSON Formatter",
      "Unit Converter",
    ],
  },
  {
    id: "devtools",
    code: "DEV",
    label: "Developer Tools",
    projects: [
      "GitHub Profile Analyzer",
      "API Testing Platform",
      "REST API Generator",
      "SQL Query Playground",
      "Code Snippet Manager",
      "Regex Tester",
      "Error Log Dashboard",
      "Docker Deployment Dashboard",
      "Dev Portfolio Builder",
      "Website Uptime Monitor",
    ],
  },
  {
    id: "misc",
    code: "MISC",
    label: "Miscellaneous",
    projects: [
      "Lost & Found Portal",
      "Complaint Management System",
      "Movie Recommendation App",
      "Travel Planner",
      "Smart Event Management System",
    ],
  },
];

export const TOTAL_MINOR_PROJECTS = MINOR_CATEGORIES.reduce(
  (sum, cat) => sum + cat.projects.length,
  0
);
